name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSKEY }}

    - name: Build Docker image for validation (PRs)
      if: github.event_name == 'pull_request'
      uses: docker/build-push-action@v2
      with:
        load: true
        tags: bertoja/pantryplanner:pr-${{ github.run_number }}
        platforms: linux/amd64,linux/arm64/v8

    - name: Build and push Docker image (main and tags)
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          bertoja/pantryplanner:${{ github.ref == 'refs/heads/main' && 'stable-main' || github.ref_name }}
          ${{ startsWith(github.ref, 'refs/tags/v') && 'bertoja/pantryplanner:latest' || '' }}
        platforms: linux/amd64,linux/arm64/v8
