name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag bertoja/pantryplanner:pr-${{ github.run_number }}

    - name: Push Docker image
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          bertoja/pantryplanner:${{ github.ref == 'refs/heads/main' && 'stable-main' || github.ref_name }}
          bertoja/pantryplanner:latest
